# Generated by Django 5.2.8 on 2025-11-24 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('rating', models.FloatField()),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='CafeProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='cafe_profile_pictures/')),
                ('bio', models.TextField(blank=True)),
                ('home_city', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cafe_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_photos/')),
                ('caption', models.TextField(blank=True)),
                ('favorite_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.favoriteitem')),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('google_rating', models.FloatField(blank=True, null=True)),
                ('image', models.URLField(blank=True)),
                ('tags', models.ManyToManyField(blank=True, to='project.tag')),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_visited', models.DateField()),
                ('user_rating', models.FloatField()),
                ('amount_spent', models.FloatField()),
                ('notes', models.TextField(blank=True)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cafe')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cafeprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Sticker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sticker_type', models.CharField(max_length=255)),
                ('x_position', models.FloatField()),
                ('y_position', models.FloatField()),
                ('rotation', models.FloatField()),
                ('scale', models.FloatField()),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='project.visit')),
            ],
        ),
        migrations.AddField(
            model_name='favoriteitem',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.visit'),
        ),
    ]
