# Generated by Django 5.2.8 on 2025-11-24 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='stickers/'),
        ),
    ]
