# Generated by Django 5.2.8 on 2025-11-27 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_visitphoto'),
    ]

    operations = [
        migrations.CreateModel(
            name='CafeWish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('visited', models.BooleanField(default=False)),
                ('cafe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cafe')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.cafeprofile')),
            ],
            options={
                'unique_together': {('profile', 'cafe')},
            },
        ),
    ]
