# Generated by Django 5.2.8 on 2025-11-27 21:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_cafewish'),
    ]

    operations = [
        migrations.CreateModel(
            name='StickerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('image', models.ImageField(upload_to='sticker_options/')),
            ],
        ),
        migrations.AlterField(
            model_name='cafe',
            name='google_rating',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
