# Generated by Django 5.2.8 on 2025-11-27 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_stickertype_alter_cafe_google_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='sticker_type',
        ),
        migrations.AddField(
            model_name='sticker',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='placed_stickers', to='project.stickertype'),
            preserve_default=False,
        ),
    ]
