# Generated by Django 5.2.8 on 2025-12-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_cafe_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
