# Generated by Django 5.2.8 on 2025-12-07 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_cafe_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafeprofile',
            name='theme_preference',
            field=models.CharField(choices=[('default', 'Default Theme 🎀'), ('dark', 'Midnight Theme 🌑'), ('forest', 'Forest Theme 🌿'), ('ocean', 'Ocean Theme 🌊')], default='default', max_length=50),
        ),
    ]
