# Generated by Django 5.2.8 on 2025-12-07 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_cafeprofile_theme_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafeprofile',
            name='theme_preference',
            field=models.CharField(choices=[('default', 'Default Theme 🎀'), ('dark', 'Midnight Theme 🌑'), ('forest', 'Forest Theme 🌿'), ('ocean', 'Ocean Theme 🌊'), ('roastery', 'Roastery Theme ☕'), ('lavender', 'Lavender Theme 🪻')], default='default', max_length=50),
        ),
    ]
